### ISSUE TITLE
Bug: Advanced > Power User Preferences don't persist after container restart

### ISSUE THREAD

**Issue by desimaniac** [linuxserver/docker-resilio-sync#7]
Any options set don't persist after container restart, but does remember the login I set the beginning. Also set GID and UID as well. 

BT Sync's docker container can save Power User Preferences, but have no option to set GID/UID, which is why I don't use it.

**Comment by thelamer** [comment]
So unfortunately the program needs to be restarted to save certain advanced parameters. Because there is no restart option in the web-ui you will need to execute a kill host side: 

```
sudo docker exec resilio-sync /bin/bash -c 'kill $(pidof rslsync)'
```
This will save the parameters to the config file and they will persist container restarts. If you want a better solution reach out to their team to add a restart button, not sure why they left it out. 

https://github.com/bt-sync/sync-docker

**Comment by desimaniac** [comment]
@thelamer The official container saves the option without having to restart.  That's all I was trying to say.

**Comment by screendriver** [comment]
Same question here @thelamer: why do we have to manually execute `sudo docker exec resilio-sync /bin/bash -c 'kill $(pidof rslsync)'` and with the official container not? 🤔

**Comment by lludlow** [comment]
The startup options use sync.conf    
make the changes there and they are permanent
